name: Özer Config
version: 1.0.0
schema: v1
models:
  - name: Minimax M2.7
    provider: ollama
    apiBase: http://localhost:11434
    model: minimax-m2.7:cloud
    roles:
      - chat
      - edit
      - apply
      - autocomplete

mcpServers:
  - name: Codebase Memory
    command: /Users/nuvocode/.local/bin/codebase-memory-mcp
  - name: Grep AI
    command: grepai
    args:
      - mcp-serve
